### PR TITLE
render piece tile and card

### PR DESCRIPTION
**Pull request by pickledolives**

### CODE REVIEW

**Review by kierstenthamm — APPROVED** [review]

**Comment by pickledolives** [comment]
image

**Comment by pickledolives** [comment]
@kierstenmounce I added a screenshot so you can better see what the change actually does. Sorry, should have thought of that earlier.

Please re-review having this additional info.

**Comment by pickledolives** [comment]
@kierstenmounce resolved some merge conflicts and also discovered and replaced some "magic numbers".

Please re-review and re-approve

**Review by kierstenthamm — APPROVED** [review]
It's so exciting!

**Pull request merged**
